#!/bin/bash

function show_help()
{
    echo "Використовуйте: $0 [--help | --version] | [висота_ялинки ширина_снігу]"
}

function show_version()
{
	echo "Програма $0, версія 0.1"
}

if [[ "$1" == "--help" ]]; then
    show_help
    exit 0
elif [[ "$1" == "--version" ]]; then
    show_version
    exit 0
fi

if [ "$#" -ne 2 ]; then
    show_help
    exit 1
fi

half_height=$(( $1 / 2 ))
tree_height=$(( half_height * 2 ))

snow_width=$2
if (( snow_width % 2 == 0 )); then
    snow_width=$(( snow_width - 1 ))
fi

if [ "$tree_height" -le 0 ] || [ "$snow_width" -le 0 ]; then
    echo "Аргументи повинні бути додатними числами!" >&2
    exit 1
fi

if [ "$tree_height" -lt 8 ] || [ "$snow_width" -lt 7 ]; then
    echo 'Недостатні розміри для побудови ялинки' >&2
    exit 1
fi

if (( tree_height - 1 != snow_width )); then
    echo "висота_ялинки занадто велика для заданої ширини снігу ($snow_width)" >&2
    echo 'ширина ярусів має бути на 2 менша за ширину снігу' >&2
    exit 1
fi

symbol='*'
function draw_branches()
{
  local height=$1
  local current_width=$2

  local counter=1
  until [ "$counter" -ge "$height" ]; do
   spaces=$(( (snow_width - current_width) / 2 ))
   printf "%*s" "$spaces" ''
   for (( i = 0; i < current_width; i++ )); do
    printf "%s" "$symbol"
   done
   echo ''
   current_width=$(( current_width + 2 ))
   (( counter++ ))
   symbol=$([ "$symbol" = '*' ] && echo '#' || echo '*')
  done
}

#draw branches
draw_branches "$half_height" 1
draw_branches $(( half_height - 1 )) 3

spaces=$(( (snow_width - 3) / 2 ))
for i in 1 2; do
 printf "%*s" "$spaces" ''
 printf "%s\n" '###'
done

counter=1
while [ "$counter" -le "$snow_width" ]; do
 printf "%s" '*'
 (( counter++ ))
done

echo ''
